### ISSUE TITLE
"Lost connection to MySQL server" while deploying to an AKS cluster

### ISSUE THREAD

**Issue by orfeas-k** [canonical/mysql-k8s-operator#394] opened 2024-03-19 10:11 UTC
I deployed mysql-k8s from 8.0/stable (rev 113) to AKS (as part of CKF) and stumbled on the following errors (both katib-db and kfp-db use mysql-k8s): [logs](https://pastebin.canonical.com/p/VYydvr8XxP/). Here are also the full logs of the CI run 
[ci-logs.txt](https://github.com/canonical/mysql-k8s-operator/files/14649061/ci-logs.txt)

## Steps to reproduce
This is intermittent but deploying CKF to an AKS cluster is what is needed in order to reproduce. You can trigger the [Create an AKS cluster and deploy CKF workflow](https://github.com/canonical/bundle-kubeflow/actions) that CKF team has (it will be merged in the following days).

## Expected behavior
MySQL server is healthy and functional

## Actual behavior
MySQL server isn't responding

## Versions
Operating system:   Ubuntu 22.04.4 LTS
Juju CLI: 3.1.7-genericlinux-amd64
Juju agent: 3.1.7
Charm revision: 113
AKS: 1.26

## Log output
Juju debug log: [juju-debug-log-replay.txt](https://github.com/canonical/mysql-k8s-operator/files/14649065/juju-debug-log-replay.txt)

**Comment by orfeas-k** [comment] 2024-04-09 15:02
MySQL failed again in the CI when deploying to AKS with the following [logs](https://pastebin.canonical.com/p/7v5TYpR5mF/) in this [run](https://github.com/canonical/bundle-kubeflow/actions/runs/8608429604/job/23590771899#step:9:2143).

This time it was deployed from `8.0/edge` and it uses revision `136`. This is something that I 'm getting let's say 1 out of 5 times or so when deploying to AKS. (you can see that one MySQL instance is healthy in the same deployment) 

Here are the complete CI logs for future reference [logs_22556141130.zip](https://github.com/canonical/mysql-k8s-operator/files/14920338/logs_22556141130.zip).

**Comment by paulomach** [comment] 2024-04-11 18:25
For record, I could not reproduce it after multiple tries on AKS, using same setup as the test.
I believe this bug is related to [juju/pebble lp#2052517](https://bugs.launchpad.net/juju/+bug/2052517), fixed on 3.4.1+

**Comment by paulomach** [comment] 2024-07-25 12:42
Hi @orfeas-k this was released/fixed on PR #458 and it's in edge.

**Closed by paulomach** 2024-07-25 12:42 UTC
Labels: bug
