### ISSUE TITLE
mysqld fails to initialise and startup

### ISSUE THREAD

**Issue by javacruft** [canonical/mysql-k8s-operator#111] opened 2022-10-26 15:25 UTC
### Bug Description

On deployment, the mysql operator fails to init/start

### To Reproduce

juju deploy mysql-k8s

### Environment

mysql-k8s r21
microk8s 1.25/stable
juju 2.9.34

### Relevant log output

```shell
unit-mysql-0: 15:19:19 INFO juju.worker.uniter.operation ran "leader-elected" hook (via hook dispatching script: dispatch)
unit-mysql-0: 15:19:21 INFO juju.worker.uniter.operation ran "mysql-pebble-ready" hook (via hook dispatching script: dispatch)
unit-mysql-0: 15:19:22 INFO juju.worker.uniter.operation ran "database-storage-attached" hook (via hook dispatching script: dispatch)
unit-mysql-0: 15:19:26 INFO juju.worker.uniter.operation ran "config-changed" hook (via hook dispatching script: dispatch)
unit-mysql-0: 15:19:26 INFO juju.worker.uniter found queued "start" hook
unit-mysql-0: 15:19:27 INFO unit.mysql/0.juju-log Running legacy hooks/start.
unit-mysql-0: 15:21:03 INFO juju.worker.uniter.operation ran "start" hook (via hook dispatching script: dispatch)
unit-mysql-0: 15:21:05 ERROR unit.mysql/0.juju-log Exited with code 1. Stderr:
unit-mysql-0: 15:21:05 ERROR unit.mysql/0.juju-log   2022-10-26T15:21:05.558094Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please u
se SET GLOBAL host_cache_size=0 instead.
unit-mysql-0: 15:21:05 ERROR unit.mysql/0.juju-log   2022-10-26T15:21:05.558217Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.30-0ubuntu0.22.04.1) initializing of server in progress as process
 15
unit-mysql-0: 15:21:05 ERROR unit.mysql/0.juju-log   2022-10-26T15:21:05.560058Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
unit-mysql-0: 15:21:05 ERROR unit.mysql/0.juju-log   2022-10-26T15:21:05.560066Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the ser
ver added to it.
unit-mysql-0: 15:21:05 ERROR unit.mysql/0.juju-log   2022-10-26T15:21:05.560143Z 0 [ERROR] [MY-010119] [Server] Aborting
unit-mysql-0: 15:21:05 ERROR unit.mysql/0.juju-log   2022-10-26T15:21:05.560302Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.30-0ubuntu0.22.04.1)  (Ubuntu).
unit-mysql-0: 15:21:06 INFO juju.worker.uniter.operation ran "mysql-pebble-ready" hook (via hook dispatching script: dispatch)
unit-mysql-0: 15:21:08 INFO juju.worker.uniter.operation ran "database-peers-relation-changed" hook (via hook dispatching script: dispatch)
unit-mysql-0: 15:22:10 INFO juju.worker.uniter.operation ran "database-relation-joined" hook (via hook dispatching script: dispatch)
```

**Comment by javacruft** [comment] 2022-10-27 06:23
I'm going to thrash this with 3.0/edge as this may contain some related fixes.

**Comment by paulomach** [comment] 2022-10-27 15:00
> I'm going to thrash this with 3.0/edge as this may contain some related fixes.

Fair. I did a batch of deployments with juju-2.9.35, switching agent versions (from 2.9.29 to 2.9.35) but they went fine.

**Comment by paulomach** [comment] 2022-10-30 10:30
mysql-server checks for files on designated repository, ignoring only `.` files and `lost+found` - so there something else at play.

**Comment by javacruft** [comment] 2022-11-17 10:52
I think I managed to capture this again - it looks like the first attempt to init mysql failed with a socket timeout via pebble, and then the unit declares it storage as dirty and un-usable:

[mysql-debug-log.txt](https://github.com/canonical/mysql-k8s-operator/files/10030691/mysql-debug-log.txt)

DEBUG enabled for that one so quite a bit of log.

**Comment by javacruft** [comment] 2022-11-17 10:52
I think I managed to capture this again - it looks like the first attempt to init mysql failed with a socket timeout via pebble, and then the unit declares it storage as dirty and un-usable:

[mysql-debug-log.txt](https://github.com/canonical/mysql-k8s-operator/files/10030691/mysql-debug-log.txt)

DEBUG enabled for that one so quite a bit of log.

**Comment by taurus-forever** [comment] 2023-03-06 11:11
Closing/reopening to create Jira ticket and schedule the fix.

**Comment by paulomach** [comment] 2023-03-15 19:22
Not able to reproduce on current setup (on 10 attempts, all went well):
microk8s 1.26.1
juju 2.9.42
mysql-k8s r43

**Closed** 2023-03-16 13:49 UTC
Labels: bug
